class Codes:
    REGISTER_RESPONSE_CODE = 2100
    REGISTER_REQUEST_CODE = 600

    LIST_CLIENT_RESPONSE_CODE = 2101
    LIST_CLIENT_REQUEST_CODE = 601

    
    GET_PUBLIC_KEY_RESPONSE_CODE = 2102
    GET_PUBLIC_KEY_REQUEST_CODE = 602

    SEND_MESSEGE_RESPONSE_CODE = 2103
    SEND_MESSEGE_REQUEST_CODE = 603

    GET_MESSEGES_RESPONSE_CODE = 2104
    GET_MESSEGES_REQUEST_CODE = 604

class Sizes:
    CLIENT_NAME_SIZE = 255
    CLIENT_ID_SIZE = 16
    PUBLIC_KEY_SIZE = 160
    MESSAGE_ID_SIZE = 4